name: Mi Primer Workflows

on: push

jobs:
    primer_job:
        runs-on: ubuntu-latest
        steps:
        - name: Mensaje de Bienvenida
          run: echo "Mi github Action Job"

        - name: List file
          run: ls

        - name: Read file
          run: cat REARME.md
