name: Mi Primer Workflows

on: push

jobs:
    primer_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: List and Read file
          run: |
           echo "Mi github Action Job"
           ls - ltra
           cat README.md
           
        - name: Generate ASCII 
          run:  cowsay -f dragon "Run for cover, I am a Dragon ... EaWs" > dragon.txt

       # - name: List file
       #   run: ls

       # - name: Read file
       #   run: cat REARME.md
